MAC_profile/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^profile/$', 'MAC_profile.views.view_profile', name="self_user_view"),
    url(r'^profile/(?P<user>\d+)/$', 'MAC_profile.views.view_profile', name="user_view"),
    url(r'^login/$','django.contrib.auth.views.login',{'template_name': 'accounts/login.html'},name="login"),
    url(r'^logout/$','MAC_profile.views.logoutview',name="logout"),
    url(r'^register/$','MAC_profile.views.registration',name="register"),
    url(r'^newpass/$','MAC_profile.views.new_pass',name="new_pass"),
)

MAC_profile/forms.py
from django import forms
from MAC_profile import models



class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=30, label = "Username",widget = forms.TextInput(attrs={'required':'required'}))
    password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'required':'required'}), label = "Password")
    passwordConfirm = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'required':'required'}), label = "Confirm Password")
    gender = forms.ChoiceField(choices=models.GENDERS,label="Gender")
    email = forms.EmailField(label="Email Address", widget = forms.TextInput(attrs={'required':'required','placeholder':'Enter a Email Valid Address'}))
    test = forms.CharField(max_length=6, label = "What University is this Club based out of?",widget = forms.TextInput(attrs={'required':'required'}))

class PassResetForm(forms.Form):
    username = forms.CharField(max_length=30, label = "Username",widget = forms.TextInput(attrs={'required':'required'}))
    reset_code = forms.CharField(max_length=200, label = "Reset Code",widget = forms.TextInput(attrs={'required':'required'}))

class NewPassForm(forms.Form):
    old_password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'required':'required'}), label = "Old Password")
    password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'required':'required'}), label = "New Password")
    passwordConfirm = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'required':'required'}), label = "Confirm New Password")

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('display_name', 'tpp', 'ppp', 'location', 'gender', 'timezone', 'avatar_local', 'blurb', 'sig', 'website_url', 'website_text', 'steam_account', 'psn_account', 'xbox_account')

MAC_profile/templates/accounts/login.html
{% extends 'base_html.html' %}
{% load static %}
{% block titleextra %} - Login{% endblock %}

{% block main %}

<div class="login">
{% if user.is_authenticated %}
<h3>You are already logged in</h3>
{% else %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<form method="post" class="form-horizontal" action="/accounts/login/">
<fieldset>
<legend>Login</legend>
{% csrf_token %}
<div class="control-group">
	<label class="control-label" for="id_username">{{ form.username.label }}</label>
	<div class="controls">
		{{ form.username }}
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="id_password">{{ form.password.label }}</label>
	<div class="controls">
		{{ form.password }}
	</div>
</div>
<div class="control-group">
	<div class="controls">
		<button type="submit" class="btn" >Log in</button>
	</div>
</div>
<input type="hidden" name="next" value="{{ next }}" />
</fieldset>
</form>
{% endif %}
</div>

{% endblock %}


{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_login");
menuItem.className = "active";
</script>
{% endblock %}

MAC_profile/templates/accounts/new_pass.html
{% extends 'base_html.html' %}
{% load static %}
{% block titleextra %} - Change Password{% endblock %}

{% block main %}

<div class="register">
<form method="post" class="form-horizontal" action="/accounts/newpass/">
<fieldset>
<legend>Set New Password</legend>
{% csrf_token %}
<div class="control-group">
	<label class="control-label" for="id_old_password">{{ form.old_password.label }}</label>
	<div class="controls">
		{{ form.old_password }}
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="id_password">{{ form.password.label }}</label>
	<div class="controls">
		{{ form.password }}
	</div>
</div>
<div class="control-group">
	<label class="control-label" for="id_passwordConfirm">{{ form.passwordConfirm.label }}</label>
	<div class="controls">
		{{ form.passwordConfirm }}
	</div>
</div>

<div class="control-group">
	<div class="controls">
		<input type="submit" class="btn" value="Change Password" />
	</div>
</div>
</fieldset>
</form>
</div>

{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_new_pass");
menuItem.className = "active";
</script>
{% endblock %}

MAC_profile/templates/accounts/profile.html
{% extends 'base_html.html' %}
{% load static %}
{% load cache %}
{% block titleextra %} - User - {{ usr.username }}{% endblock %}
{% block main %}
<div class="col-md-4">
	<dl><dt>Profile Avatar:</dt><dd><img src="{{usr.profile.avatar}}" alt="{{usr.username}}'s Avatar" class="img-rounded" ></dd></dl>
</div>
{% cache 500 profile %}
<div class="col-md-8">
	<dl class="dl-horizontal">
		<dt>Username:</dt><dd>{{usr.username}}</dd>
		<dt>Display Name:</dt><dd>{{usr.profile.display_name}}</dd>
		<dt>Location:</dt><dd>{{usr.profile.location}}</dd>
		<dt>Website:</dt><dd><a href="{{usr.profile.website_url}}">{{usr.profile.website_text}}</a></dd>
		<dt>User Text:</dt><dd>{{usr.profile.blurb}}</dd>
		<dt>Signature:</dt>
		<dd>{{usr.profile.sig_shown|safe }}</dd>
	</dl>
</div>
{% endcache %}
{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_profile");
menuItem.className = "active";
</script>
{% endblock %}

MAC_profile/templates/accounts/profile_edit.html
{% extends 'base_html.html' %}
{% load static %}
{% load bbcode %}
{% block titleextra %} - Edit Profile{% endblock %}
{% block main %}
<h2>{{usr.username}}</h2>

{% endblock %}

MAC_profile/templates/accounts/register.html
{% extends 'base_html.html' %}
{% load static %}
{% block titleextra %} - Registration{% endblock %}

{% block main %}

<div class="register">
{% if user.is_authenticated %}
<h2>Registration</h2>
<h3>You are already logged in</h3>
{% else %}
<form method="post"  class="form-horizontal" action="/accounts/register/">
<fieldset>
<legend>Registration</legend>

{% csrf_token %}
<div class="control-group">
	<label class="control-label" for="id_username">{{ form.username.label }}</label>
	<div class="controls">
		{{ form.username }}
	</div>
</div>

<div class="control-group">
	<label class="control-label" for="id_password">{{ form.password.label }}</label>
	<div class="controls">
		{{ form.password }}
	</div>
</div>

<div class="control-group">
	<label class="control-label" for="id_passwordConfirm">{{ form.passwordConfirm.label }}</label>
	<div class="controls">
		{{ form.passwordConfirm }}
	</div>
</div>

<div class="control-group">
	<label class="control-label" for="id_email">{{ form.email.label }}</label>
	<div class="controls">
		{{ form.email }}
	</div>
</div>

<div class="control-group">
	<label class="control-label" for="id_gender">{{ form.gender.label }}</label>
	<div class="controls">
		{{ form.gender }}
	</div>
</div>

<div class="control-group">
	<label class="control-label" for="id_test">{{ form.test.label }}</label>
	<div class="controls">
		{{ form.test }}
	</div>
</div>

<div class="control-group">
	<div class="controls">
		<button type="submit" class="btn">Register</button>
	</div>
</div>
</fieldset>
</form>
{% endif %}
</div>

{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_register");
menuItem.className = "active";
</script>
{% endblock %}